export const CART_ACTION = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ITEM_FROM_CART_WITH_QUANTITY: "REMOVE_ITEM_FROM_CART_WITH_QUANTITY",
  ADD_CART_COUNT: "ADD_CART_COUNT",
  REMOVE_CART_COUNT: "REMOVE_CART_COUNT",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
};
